variable "project_name" {}
variable "region" {}
variable "gce_name" {}
variable "zone" {}
variable "machine_type" {}
variable "boot_disk_type" {}
variable "boot_disk_image" {}
variable "credential" {}
variable "nat_ip" {}
variable "network_tier" {}